name: GitHub Repository Replica

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: "GitHub Personal Access Token"
        required: true
        type: string

      source_repo_url:
        description: "Source Repository URL"
        required: true
        type: string

      target_repo_name:
        description: "Target Repository Name"
        required: true
        type: string

jobs:
  clone-repository:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract Source Repo Details
        id: repo
        run: |
          REPO_PATH=$(echo "${{ github.event.inputs.source_repo_url }}" | sed 's#https://github.com/##' | sed 's#.git##')
          echo "repo_path=$REPO_PATH" >> $GITHUB_OUTPUT

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ github.event.inputs.github_token }}
        run: |
          gh auth status

      - name: Create Target Repository
        env:
          GH_TOKEN: ${{ github.event.inputs.github_token }}
        run: |

   
